<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends EntityRepository
{
     public function getExercices()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('e')
                ->from('BZBlogBundle:Exercice', 'e')
                ->andWhere('e.estsupprimer =:supp')
                ->setParameter('supp', false);
        $qb->orderBy('e.annee', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
}
