<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NiveauAlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauAlerteRepository extends EntityRepository
{
      public function getNiveauAlertes()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n')
                ->from('BZBlogBundle:NiveauAlerte', 'n')
                ->andWhere('n.estsupprimer =:supp')
                ->setParameter('supp', false);
        $qb->orderBy('n.libelle', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
}
