<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjetClassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetClassementRepository extends EntityRepository
{
    public function getObjetClassements()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('o')
                ->from('BZBlogBundle:ObjetClassement', 'o')
                ->andWhere('o.estsupprimer =:supp')
                ->setParameter('supp', false);
        $qb->orderBy('o.ref', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
    
}
