<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousRubriqueControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousRubriqueControleRepository extends EntityRepository
{
}
