<?php

namespace BZ\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends EntityRepository
{
     public function getAnneeArchives($exercice)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
                ->from('BZArchiveBundle:Archive', 'a')
                ->andWhere('a.estsupprimer =:supp')
                ->andWhere('a.exercice =:exo')
                ->setParameter('supp', false)
                ->setParameter('exo', $exercice);
        $qb->orderBy('a.dateArchive', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
    public function getAnneeCategorieArchives($exercice, $categorie)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
                ->from('BZArchiveBundle:Archive', 'a')
                ->andWhere('a.estsupprimer =:supp')
                ->andWhere('a.exercice =:exo')
                ->andWhere('a.categoriearchive =:categ')
                ->setParameter('supp', false)
                ->setParameter('categ', $categorie)
                ->setParameter('exo', $exercice);
        $qb->orderBy('a.dateArchive', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
    
    public function getArchivesCategorie($exercice)
    {
        $query = $this->_em->createQuery('SELECT c.id as id, c.libelle as libelle, COUNT(a.id)  as total FROM BZArchiveBundle:Archive a, BZArchiveBundle:CategorieArchive c WHERE a.categoriearchive = c.id AND a.exercice =:annee AND a.estsupprimer = 0 AND c.estsupprimer = 0 GROUP BY c.id, c.libelle');
        $query->setParameter('annee', $exercice);
        return $query->getArrayResult();
    }
    public function getArchivesTotal()
    {
        $query = $this->_em->createQuery('SELECT e.id as id, e.annee as annee, COUNT(a.id)  as total FROM BZArchiveBundle:Archive a, BZBlogBundle:Exercice e WHERE a.exercice = e.id AND a.estsupprimer = 0 AND e.estsupprimer = 0 GROUP BY e.id, e.annee' );        
        return $query->getArrayResult();
    }
}
