<?php

namespace BZ\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieArchiveRepository extends EntityRepository
{
     public function getCategorieArchives()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('BZArchiveBundle:CategorieArchive', 'c')
                ->andWhere('c.estsupprimer =:supp')
                ->setParameter('supp', false);
        $qb->orderBy('c.libelle', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
}
