<?php

namespace BZ\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentArchiveRepository extends EntityRepository
{
}
