<?php

namespace BZ\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisibiliteArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisibiliteArchiveRepository extends EntityRepository
{
}
